---
# Deployment configuration for Next.js application
# Este archivo asume que el repositorio Git est치 clonado directamente en el Application Root
# Si el repo est치 en la misma carpeta de la app, solo necesitamos instalar y build
deployment:
  tasks:
    - export NODE_ENV=production
    # Instalar dependencias (sin --production para incluir devDependencies necesarias para build)
    - /usr/local/bin/npm ci
    # Hacer build de producci칩n
    - /usr/local/bin/npm run build
    # Reiniciar la aplicaci칩n Node.js (Passenger detecta el cambio y reinicia)
    - /bin/touch tmp/restart.txt

